spring.application.name=workout-tracker
springdoc.default-produces-media-type=application/json
server.port=4000

# -- Defined in docker configuration, uncomment if not running docker container --
# h2 database config
#spring.h2.console.path=/h2-console
#
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=admin
#spring.datasource.password=admin
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#
#spring.sql.init.mode=always